[tool.poetry]
name = "feature-selection"
version = "0.1.0"
description = "Feature selection for scikit-learn estimators"
authors = ["Ryan Homer <ryan.homer@alumni.ubc.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
